language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: CAL6BKAbR6qnzMSPqZ2v6igVhrAb1R+fGeCzZxn5QGaCDSgNq0BKfbSFSQQ0I88htkA1HCQlmGiFE4csikF0mYsfjZcZ71q713pTUdoszEKsSU/8w8RXP9tXzXMquEf5yK0AWC3TZDSOb3ey336QD0rye+U7k8nmS5s2SekVL1gTnAoLOQIHAcW7LjG6KOU4EdZYZdFT1VMdUbjC7ZlRZHyXu8QRtnLWsOkpZFSf5kkiAbzuJQBS/7kpXZL/uZqHHOuufQW54wAMoBF5ZIra2GnqO/AS1XhYFkug7/cLVJfow32ffFrt3PuANaG5wKX+3V7cPX3RWBmdRuStNjON4SGf9TkHzwCOVxKp5S2iKddQLn0Mx14PePKTu161gNQ6mf11Js9EuJrMuhpFVAVTSdorHCXXoQQWmI3v3KcUFpKOBruV8Fx5B5T1nZYmpITBTPn6x/9D4tewxsSx8tO/rngE9hTArKcQsijsLFiRy5M4vJFczS6wxMmdXd+QUAw3S3LIORnrRcqvizs+jDJ/IDZgF9VQIE2PSJH6Rjm2/ioKYbaL7zagWdbKT90+O2Pnlp3HrrmCnsAVbAgKhbBwyqkkxay1F6tuFMIw33rM9K/Kc4xjGGscl5VelQy7APtHIngrISlUeaCH9R/dD1XPcGN5Mvd+ToFCR9ABeXuVY5I=
  - secure: RTM6RIbkfpFjUbm6o0YrsvYr5k90GSk0T/jNT6i98NCh2PBND6hNzvCw+6jK1/IJrnseafvhwAvV/A7hMcp9gAnMw26QFjJnK8n+OsMfrk4El02k+wJaUvnbDN2EyQfXjxCEBb62f9ld1sR9kPMrVYiJM8ZZvH9H4p8ecF0eod4BFaKXcHzk0A2zdjBWUBICV7mf7wabBNWz1dP/NdN8ICE3iugy1pfeZz0oDwrUos7syPC4uhEvPMT3N7/Dvs4OD8wxZMhAWGCZ3xjJDLr94Nv8hmM3hBXiJkLXAgoytmpSzm70/cmTQKP189Z+EY8S+1nJIudAtexHt39vA31FEEdEvK84m+sanh/J3lZDoYQZqlDzuG3S4BeqRtmHid9pkl6Aq3qCRHcclzJueFslgTX+rxEKVANo5pOBtPi97j5tLg3dzYRyVJaO29oFXV4PAAmQ+i9dRANa5l4B8g4oKhDccdfeO0WBKBul4E6i2P2zAGKp3bwmZSxiyNOMvPVBzDQk5yCZufxMdJXyr9G4ZxzHHGIkhhotoK7NKV2/2NawviLSd0LFlnxam2YoWw0hYJWjXhGAKrWN/LPyS20Sqe6y5gOODgVtXy7c8NFImWqpmmdktETWsRmIv9bRT4QFL9oszYwCuLdq4f01eYabGCJ/5kEkZYnvVZ9qJP6xXy8=
  - secure: p0uY/eMIz31E2hUxbOWb4ZcwbqpBxo3i33ZT3rED/fWuBp2MXH7pz0W8TpCNPw9Onhw5hm/v7i0t4rmylclkqJz+mdibUoIH7LFlqF8OlqFXAoz8iZXhvPk29MWTwRkbNqjIqJxsP7QlwTzZoMM+hi/zM1k5xRzdK5LXXL2V/k8Y2M0MyL1BQBiGCY6UW4TSvz60dlCCLE3zSly2PBU03ZLyOwLT5UT8nua51b/asLUB35kW3oDSgkGxdeDu29hQwIC/XxyS59ExD80S8dN32roCMrIHnOrEPSCyAG62OEFM3+hj05ywq2bHeYIXn09WvotqJi4KlPLSK0/DYcKWpDu0Cj4vHfy0ZWkoachpQ7shvYEOyPbsQQSMZk0mOQDmxUk9UpMV7bbrtTHMxjVahvMEfYzfzJj0oNZigD7o1DXqziHs/wG5HOg9nlBK1uJRwTenoyJWrt5uEB+cis60sLgOPaVSzgOB5VIFOLN3dDBhtvwxpo7hrCn3Q4eNBaiI5HS1390bNRvihVGC87hI2d+KHW4h7748C5aWm4yQLDk+LV8FVPAomhByKuBgcGnndLaaRz59tfgOPjggx+Kx3bErurUx6ZeoFMdcMgSgn6PhVnUjAwGI2QZuHNJH76RBRT5YaPiB0GV3Y70+cM1anKVCB8dOkXIzLejjDgJHN8Q=

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_bf19104499f6_key -iv $encrypted_bf19104499f6_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
